### ISSUE TITLE
Use Rollup to bundle and have it split in files

### ISSUE THREAD

**Issue by TheGLander** [DarkSoul1800/DarkysBatch#2]
Yeah, title

(I am Z man/G lander)

**Comment by DarkSoul1800** [comment]
> 
> 
> Yeah, title
> 
> (I am Z man/G lander)

I honestly have no idea what you mean, sorry :/
Also i saw this issue since Day 1 but never replied, i was always busy with other stuff.

**Comment by zyudneko** [comment]
Oh, that’s fine
I meant it should be handier if you had some bundler like rollup or webpack so you can have the source code all split it files, and the bundler would automatically bundle them in different versions, like only cheevos, only upgrades, etc.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DarkSoul1800** [comment]
hmmm alright that does sound nice, I'll see if i can someday figure out how to work that out, thank you.

**Comment by hyoretsu** [comment]
Should be re-opened, since the whole implementation of this was reverted.
